# Generated by Django 4.1.3 on 2022-12-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='Introduction_brief',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Num_of_courses_completed',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Num_of_courses_enrolled',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Num_of_enrolled_students',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Qualification',
        ),
        migrations.CreateModel(
            name='Joining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=200)),
                ('User_email', models.EmailField(max_length=254)),
                ('Staff_name', models.CharField(max_length=200)),
                ('Staff_email', models.EmailField(max_length=254)),
                ('Joining_date', models.DateField(auto_now_add=True)),
                ('Teacher_response', models.CharField(max_length=200)),
                ('notify', models.CharField(max_length=200, null=True)),
                ('join_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='read.registration')),
            ],
        ),
    ]
