# Generated by Django 4.1.4 on 2023-01-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0002_remove_registration_introduction_brief_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='Average_review_rating',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Num_of_reviews',
        ),
    ]
