# Generated by Django 4.1.4 on 2023-01-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0003_remove_registration_average_review_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joining',
            name='Teacher_response',
        ),
    ]
