# Generated by Django 4.1.4 on 2023-01-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0005_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodect_id', models.IntegerField(max_length=200, null=True)),
                ('quantity', models.IntegerField(max_length=200, null=True)),
                ('price', models.FloatField(max_length=200, null=True)),
                ('total', models.FloatField(max_length=200, null=True)),
                ('discount', models.CharField(max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
