# Generated by Django 4.1.4 on 2023-01-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='prodect_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
