# Generated by Django 4.1.4 on 2023-01-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0008_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
    ]
