# Generated by Django 4.1.4 on 2023-01-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0012_remove_cart_product_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
