# Generated by Django 4.1.4 on 2023-01-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0013_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
