# Generated by Django 4.1.4 on 2023-01-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0015_cart_cartitem_cart_products_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
