# Generated by Django 4.1.3 on 2023-01-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0017_cart_product_cartitem_cart_products_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
