# Generated by Django 4.1.3 on 2023-01-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0018_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
