# Generated by Django 4.1.4 on 2023-01-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0021_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
