# Generated by Django 4.1.4 on 2023-01-30 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0025_order_address_order_phone_order_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime.today, max_length=50),
        ),
    ]
