# Generated by Django 4.1.4 on 2023-01-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0027_alter_order_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
    ]
