# Generated by Django 4.1.4 on 2023-01-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0029_order_pin_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pin_code',
            new_name='pincode',
        ),
    ]
