# Generated by Django 4.1.4 on 2023-01-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0030_rename_pin_code_order_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
