# Generated by Django 4.1.4 on 2023-02-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0032_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
